fix: set logger for controller-runtime
k8sgpt-ai/k8sgpt pull request #1211
Opened 2024-08-01 07:50 UTC by yeahdongcn

Closes #1208  

## 📑 Description

Set logger for controller-runtime.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

Testing done:
- `make docker-build` -> ok
- After applying the newly built Docker image in k8sgpt-operator, this log `[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.` is no longer present.

2024-08-02 18:34 UTC, cf250024 approved these changes
I tested the changes and it works for me. Thanks.

2024-08-06 18:34 UTC, cf250024 commented
Can we put new code in pkg/server/serve.go instead of cmd/serve/serve.go?
I'm thinking this part is more related to server that cli. I tried this option prior your PR and it also works.

2024-08-07 08:52 UTC, AlexsJones commented
> Can we put new code in pkg/server/serve.go instead of cmd/serve/serve.go? I'm thinking this part is more related to server that cli. I tried this option prior your PR and it also works.

I would be supportive of that also

2024-08-07 08:55 UTC, AlexsJones requested changes
Please move this into the `pkg/server/serve.go`

2024-08-07 14:14 UTC, yeahdongcn commented
> Please move this into the `pkg/server/serve.go`

Done. @cf250024 @AlexsJones

2024-08-07 18:38 UTC, AlexsJones approved these changes

2024-08-08 06:10 UTC, merged