feat: add & remove default filter(s) to analyze.
k8sgpt-ai/k8sgpt pull request #161
Opened 2023-03-30 20:10 UTC by matthisholleville

Closes #158

## 📑 Description

This MR allows the addition of custom default filters. As discussed here https://github.com/k8sgpt-ai/k8sgpt/issues/158, it would be interesting for the user to have the possibility to manage the analyzers they are interested in and for example not have to execute PDB analyzers when they do not use them.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

I have done a lot of testing of adding/removing filters in the configuration file and have not found any side effects. If you would like me to perform additional tests, please let me know which ones.

This version does not include a breaking change.

2023-03-30 21:18 UTC, matthisholleville commented on README.md
> +k8sgpt filters add Pod Service
I just modified the documentation. Can you give me your opinion?

2023-03-30 21:31 UTC, rjchicago commented on README.md
> +k8sgpt filters add Pod Service
Yes, clear now - thank you!

2023-03-31 09:55 UTC, AlexsJones commented on README.md
> +k8sgpt filters add Pod Service
Should we comma delimit to keep it consistent with `--filter` ?

2023-03-31 10:03 UTC, AlexsJones requested changes

2023-03-31 10:03 UTC, AlexsJones commented on cmd/filters/filtersAdd.go
> +		// Verify dupplicate
```suggestion
// Verify duplicate
```

2023-03-31 10:03 UTC, AlexsJones commented on cmd/filters/filtersAdd.go
> +		uniqueFilters, dupplicateFilters := util.RemoveDuplicates(mergedFilters)
Spelling on `dupplicateFilters `

2023-03-31 10:05 UTC, AlexsJones commented
```
alex@alpha:~/Code/k8sgpt$ go run main.go filters list remove Pod
Available filters :
> Pod
> ReplicaSet
> PersistentVolumeClaim
> Service
> Ingress
alex@alpha:~/Code/k8sgpt$ go run main.go filters list
Available filters :
> Pod
> ReplicaSet
> PersistentVolumeClaim
> Service
> Ingress
```

Is this right?

2023-03-31 10:07 UTC, AlexsJones commented
```
Available filters :
> Service
> Ingress
> Pod
> ReplicaSet
> PersistentVolumeClaim
alex@alpha:~/Code/k8sgpt$ go run main.go filters remove ReplicaSet
Filter(s) ReplicaSet does not exist in configuration file. Please use k8sgpt filters add.
exit status 1
```

2023-03-31 10:08 UTC, AlexsJones commented
It looks like this would be a breaking change, we would have to ask people to regenerate their k8sgpt.yaml?

2023-03-31 10:53 UTC, matthisholleville commented on README.md
> +k8sgpt filters add Pod Service
If we want to be consistent, I suggest using: `k8sgpt add --filter` Pod.

2023-03-31 10:56 UTC, matthisholleville commented on cmd/filters/filtersAdd.go
> +var filtersAddCmd = &cobra.Command{
I don't think it's necessary to expose the command outside of the filter package. Instead, I suggest renaming `filterAddCmd` to `addCmd`.

2023-03-31 10:56 UTC, matthisholleville commented on cmd/filters/filtersRemove.go
> +var filtersRemoveCmd = &cobra.Command{
I don't think it's necessary to expose the command outside of the filter package. Instead, I suggest renaming `filtersRemoveCmd` to `removeCmd`.

2023-03-31 10:58 UTC, matthisholleville commented
No breaking change. I handle the fact that the `default_filters` key does not exist in the file.

2023-03-31 11:06 UTC, matthisholleville commented
https://github.com/k8sgpt-ai/k8sgpt/pull/161#issuecomment-1491674148

This error is correct. You are trying to remove a filter that is not defined in your configuration file. 
Isn't the error message precise enough?

```
➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters list
Available filters : 
> ReplicaSet
> PersistentVolumeClaim
> Service
> Ingress
> Pod
➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters add ReplicaSet
Filter ReplicaSet added
➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters remove ReplicaSet
Filter(s) ReplicaSet removed
```

2023-03-31 11:10 UTC, matthisholleville commented on README.md
> +k8sgpt filters add Pod Service
I will change

2023-03-31 11:31 UTC, matthisholleville commented on README.md
> +k8sgpt filters add Pod Service
It's modified.

2023-03-31 11:55 UTC, AlexsJones commented
> [#161 (comment)](https://github.com/k8sgpt-ai/k8sgpt/pull/161#issuecomment-1491674148)
> 
> This error is correct. You are trying to remove a filter that is not defined in your configuration file. Isn't the error message precise enough?
> 
> ```
> ➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters list
> Available filters : 
> > ReplicaSet
> > PersistentVolumeClaim
> > Service
> > Ingress
> > Pod
> ➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters add ReplicaSet
> Filter ReplicaSet added
> ➜  k8sgpt git:(feature/add-and-remove-filters) ./k8sgpt filters remove ReplicaSet
> Filter(s) ReplicaSet removed
> ```

Okay, so maybe this is a DX issue.
Here is the assumption I have:

As a user when I run K8sGPT I'll have default_filters enabled e.g.
```
> > ReplicaSet
> > PersistentVolumeClaim
> > Service
> > Ingress
> > Pod
```

Let's say I actually don't find Ingress information useful and just spammy in my cluster.
I then say okay `k8sgpt filter remove Ingress`
That then gives me:
```
Active:
> > ReplicaSet
> > PersistentVolumeClaim
> > Service
> > Pod
Unused:
> > Ingress
```

Maybe I didn't articulate this, but it seems we have the "built in" concept vs the "user defined default list" 

WDYT?

2023-03-31 12:57 UTC, matthisholleville commented
@AlexsJones That's very clear and makes sense. I'll make you an implementation proposal.

2023-03-31 13:47 UTC, matthisholleville commented
@AlexsJones New version available. I have taken your requests into account. Below you will find my tests:

```
➜  k8sgpt git:(feature/add-and-remove-filters) ✗ cat ~/.k8sgpt.yaml
backend_type: openai
kubernetesclient: {}
openai_key: xxxxxx                                                                                                     
➜  k8sgpt git:(feature/add-and-remove-filters) ✗ ./k8sgpt filters list
Active: 
> Service
> Ingress
> Pod
> ReplicaSet
> PersistentVolumeClaim
➜  k8sgpt git:(feature/add-and-remove-filters) ✗ ./k8sgpt filters add Pod
Duplicate filters found: Pod
➜  k8sgpt git:(feature/add-and-remove-filters) ✗ ./k8sgpt filters remove Pod
Filter(s) Pod removed
➜  k8sgpt git:(feature/add-and-remove-filters) ✗ cat ~/.k8sgpt.yaml         
active_filters:
    - ReplicaSet
    - PersistentVolumeClaim
    - Service
    - Ingress
backend_type: openai
kubernetesclient: {}
openai_key: xxxxxx
```

I also took the opportunity to rename the concept of `default_filters` to `active_filters`, which seems more meaningful to me.

2023-03-31 14:02 UTC, AlexsJones commented
This is an awesome contribution thank you @matthisholleville

2023-03-31 14:04 UTC, merged