feat: migrate api to grpc
k8sgpt-ai/k8sgpt pull request #386
Opened 2023-05-06 13:06 UTC by matthisholleville

Closes #380 

## 📑 Description

This PR migrates the k8sgpt AI API from REST to gRPC, which provides a more efficient and scalable communication protocol. The protobuf files are located in the buf.build repository at https://buf.build/k8sgpt-ai/k8sgpt. The new gRPC implementation provides improved performance and reliability, while also enabling easier integration with other gRPC-based services.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

2023-05-06 22:47 UTC, numanjatt approved these changes

2023-05-06 22:47 UTC, numanjatt approved these changes

2023-05-06 22:47 UTC, numanjatt submitted a review, later dismissed

2023-05-07 04:28 UTC, Aisuko requested changes
Hi, thanks for your contribution. Please take a look at the suggestions.

2023-05-07 04:28 UTC, Aisuko commented on pkg/server/log.go
> +			fields = append(fields, zap.Int32("status_code", int32(grpc.Code(err))))
I saw that `grpc.Code` is deprecated and it suggests using `status.Code` instead. https://pkg.go.dev/google.golang.org/grpc@v1.54.0#Code

2023-05-07 04:28 UTC, Aisuko commented on pkg/server/log.go
> +		logRequest(logger, fields, int(grpc.Code(err)), message)
Same here.

2023-05-09 07:34 UTC, AlexsJones approved these changes

2023-05-09 07:36 UTC, merged