fix: use status instead of event for pdb checking
k8sgpt-ai/k8sgpt pull request #477
Opened 2023-06-02 09:07 UTC by jianzhangbjz

Closes #476 

## 📑 Description
The PDB event is a historical record, it's not a good choice to judge `pdb` status by based on it. So, I used the `status` instead of `event` in this PR.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2023-06-02 19:21 UTC, AlexsJones commented on pkg/analyzer/pdb.go
> +					Text:          fmt.Sprintf("%s, expected pdb pod lable %s=%s", pdb.Status.Conditions[0].Reason, k, v),
```suggestion
Text:          fmt.Sprintf("%s, expected pdb pod label %s=%s", pdb.Status.Conditions[0].Reason, k, v),
```

2023-06-04 23:47 UTC, arbreezy requested changes
Update your commit message as well, to conform with release-please

2023-06-05 08:21 UTC, jianzhangbjz commented on pkg/analyzer/pdb.go
> +					Text:          fmt.Sprintf("%s, expected pdb pod lable %s=%s", pdb.Status.Conditions[0].Reason, k, v),
Updated it, thanks!

2023-06-05 09:53 UTC, AlexsJones approved these changes
LGTM, but as @arbreezy says please update commit message

2023-06-06 02:50 UTC, jianzhangbjz commented
>  please update commit message

Hi @AlexsJones @arbreezy , thanks for your review. I will squash those two commits, but, sorry, what commit message I should add? Thanks!

2023-06-06 09:21 UTC, jianzhangbjz commented
Hi @AlexsJones @AlexsJones , I updated the commit message, please let me know if any thing else is needed, thanks!
```console
    fix: use the `status` for pdb checking
    
    The PDB event is a historical record, it's not a good choice to judge the pdb latest status based on it.
    So, use the `stataus` instead of `event` to check it.
    
    Closes: #476
    
    Signed-off-by: Jian Zhang <jiazha@redhat.com>
```

2023-06-06 09:27 UTC, arbreezy approved these changes

2023-06-07 00:36 UTC, jianzhangbjz commented
Hi @AlexsJones @arbreezy, seems like the merging is blocked by `The base branch restricts merging to authorized users.`. Could you help have a look? Thanks!
<img width="708" alt="image" src="https://github.com/k8sgpt-ai/k8sgpt/assets/15416633/8dcba5c9-1e60-493d-b090-e9eb21865a72">

2023-06-07 09:51 UTC, merged