feat: add Validating/Mutating webhook analyzer
k8sgpt-ai/k8sgpt pull request #548
Opened 2023-07-07 11:55 UTC by rakshitgondwal

Closes #533 

## 📑 Description
Changes made:
- Added an analyzer for Validating Webhook that checks if the pod that webhook points to is not active.
- Added an analyzer for Mutating Webhook that checks if the pod that webhook points to is not active.

## ✅ Checks

- [s] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-07-10 08:52 UTC, AlexsJones approved these changes

2023-07-10 15:11 UTC, arbreezy commented
@rakshitgondwal would be nice to share what openai's response is as well based on the error messages you feed it

2023-07-10 16:46 UTC, rakshitgondwal commented
> @rakshitgondwal would be nice to share what openai's response is as well based on the error messages you feed it

![Screenshot from 2023-07-10 22-15-31](https://github.com/k8sgpt-ai/k8sgpt/assets/98955085/93f96d24-3e5e-444a-9d7a-fc8b9ddc708b)

2023-07-11 13:15 UTC, rakshitgondwal commented
> I also left a few comments, thanks for your contribution !

Sorry, but I can't see your comments, can you please re check?

2023-07-11 13:28 UTC, arbreezy requested changes

2023-07-11 17:54 UTC, rakshitgondwal commented on pkg/analyzer/validating-webhook.go
> +		parent, _ := util.GetParent(a.Client, value.ValidatingWebhook.ObjectMeta)
Can you help me out here? I didn't get this.

2023-07-12 10:22 UTC, AlexsJones commented on pkg/analyzer/validating-webhook.go
> +		parent, _ := util.GetParent(a.Client, value.ValidatingWebhook.ObjectMeta)
```
func GetParent(client *kubernetes.Client, meta metav1.ObjectMeta) (string, bool) {
	if meta.OwnerReferences != nil {
		for _, owner := range meta.OwnerReferences {
			switch owner.Kind {
			case "ReplicaSet":
```

You need to add a case in for these types he means @rakshitgondwal

2023-07-12 10:32 UTC, rakshitgondwal commented on pkg/analyzer/validating-webhook.go
> +		parent, _ := util.GetParent(a.Client, value.ValidatingWebhook.ObjectMeta)
Thank you. Pushed up a commit fixing this. Please have a look.

2023-07-12 12:07 UTC, AlexsJones approved these changes

2023-07-12 12:31 UTC, arbreezy approved these changes

2023-07-12 13:20 UTC, merged

2023-07-12 14:21 UTC, rakshitgondwal commented
Thank you for the merge!

2023-07-13 10:16 UTC, AlexsJones commented
![image](https://github.com/k8sgpt-ai/k8sgpt/assets/1235925/e2c2d1f6-240a-4152-b822-372cbcfa649b)


As per here, use the service-name the webhook is bound too and check if the service has pods that are active ( at least 1 )
that should be the real logic

2023-07-13 12:36 UTC, rakshitgondwal commented
I was trying out this logic, but it is not working. I added a `LabelSelector` while getting the pods to be `service.name`, then looped on the pods and check if they are running. Can you help me out with this? @AlexsJones 
```
svc := webhook.ClientConfig.Service
pods, err := a.Client.GetClient().CoreV1().Pods(a.Namespace).List(context.Background(), v1.ListOptions{LabelSelector: svc.Name})
	if err != nil {
		return nil, err
	}
	activePods := 0
	for _, pod := range pods.Items {
		if pod.Status.Phase == "Running" {
			activePods++
		}
	}
	if activePods == 0 {
		doc := apiDoc.GetApiDocV2("spec.webhook")
		failures = append(failures, common.Failure{
```

2023-07-13 13:33 UTC, AlexsJones commented
I can take a look at implementing it a version of this and seeing whats wrong later today